### ISSUE TITLE
Allow the gem to integrate with other id schemes (don't override to_param)

### ISSUE THREAD

**Issue by mcoms** [thetron/mongoid_token#27]
A feature request...  I'd like to use the gem to generate tokens in addition to mongoid-slug, so it would be good if you could specify an option not to override to_param.

**Comment by holgersindbaek** [comment]
Hi @mcoms @thetron 

How exactly did you do this with mongoid-slug? I'm not sure how my query is supposed to look. Not I just do - Listing.find(params[:id]) - but that doesn't work. I've set - override_to_param: false - so not sure what else I'm supposed to do?

**Comment by thetron** [comment]
@holgersindbaek from memory, mongoid-slug does a similar thing to this library, and attempts to check if the parameter passed into `.find(...)` looks like a MongoDB objectID. If so - it calls `super(...)` with that param, otherwise it performs the query as a token.

To have these libraries work side-by-side, I would recommend disabling both the finders and the `to_param` override, to minimise any sort of unexpected results. So something like:

```ruby
token skip_finders: true, override_to_param: false
```

If you want to query on the token, you can just use `.find_by(...)`, like this: `FooModel.find_by(:token => "123456")`.

**Comment by holgersindbaek** [comment]
@thetron Thanks for the answer. I'm still not sure how I query for both things though. Sometimes people pass in a token, sometimes a slug, so how would my query look?

FooModel.find_by(:token => "123456") || FooModel.find(:slug => "some-slug")

**Comment by digitalplaywright** [comment]
@holgesindbaek You should be able to use find directly, like e.g

FooModel.find("123456") || FooModel.find("some-slug").

**Comment by holgersindbaek** [comment]
@digitalplaywright @thetron If I add - skip_finders: true - then  FooModel.find("some-slug") works, but finding by token doesn't work.

Getting this error when trying to find with token:

Problem:
  Document(s) not found for class Listing with id(s) cjfj.
Summary:
  When calling Listing.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): cjfj ... (1 total) and the following ids were not found: cjfj.
Resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.

**Comment by thetron** [comment]
@holgersindbaek The problem is that when you call `find` it will raise an exception if it can't find a matching document - which is what you're experiencing. It's also why things like `FooModel.find("123456") || FooModel.find("some-slug")` won't work.

Both mongoid_token and mongoid-slug have strategies for _trying_ to determine if you're searching by token, slug or ObjectID and respond accordingly. However, from mongoid_token's perspective, it can't tell the difference between a slug or a token, since it just checks if the argument is a valid ObjectID, and if not - assumes it's a token.

Given your use case, I think it's probably best for you to write your own finder method, which searches across both fields. Keep in mind I haven't tested any of this, but I would probably be inclined to do something like:

```ruby
Listing.limit(1).or({:token => params[:id]}, {:slug => params[:id]}).first
```

This _won't_ raise an exception if no document is found, so obviously you'll need to handle that case. You'd probably want to have some checks elsewhere in your app to ensure that the union of tokens and slugs are unique.

**Comment by holgersindbaek** [comment]
@thetron @digitalplaywright Thanks a lot. That seems to work.

Last question. Mongoid slug seems to be checking if the slug has been used before and generates a unique slug if it has (if my-slug is taken, it becomes my-slug-1, etc). Doesn't mongoid token check if the token has been used before, so it's always a unique token that is used?

I remember reading the note in the readme, saying it had something to do with the indexes? I'm not sure how to do that part though?

**Comment by thetron** [comment]
Tokens are always unique. This is enforced by an index on the document collection. If you try to save a model instance with a duplicate token, it will raise an exception from Mongoid.

That being said (and i'm considering removal of this feature in the future), mongoid_token will _retry_ three times (by default) to generate tokens, if this exception is encountered, before bubbling the exception up to your app.

In my apps, I would generally plan for this by making the tokens a little longer than necessary

**Comment by holgersindbaek** [comment]
@thetron  K... good to hear.

What happens when you run out of tokens? Right now, I'm doing 4 characters alpha numeric (upper and lowercase), which should accommodate for a good deal of tokens. When I'm about to run out, can I just change it to 5 tokens instead?

**Comment by thetron** [comment]
Yup. You can just change the length at any time. With your 4 character, alpha numeric tokens, you've got around 15 million possible tokens. Which sounds like a lot, but if you have 150,000 `Listing` records, you're looking at a 1% chance of a collision.
